name: flutter_offline_dictionary
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  hive: ^1.4.3
  hive_flutter: any
  # For OS-specific directory paths
  path_provider: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: any
  build_runner: any

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
